### ISSUE TITLE
Le contour est absent lorsque format=geojson

### ISSUE THREAD

**Issue by Morendil** [etalab/api-communes#62]
Est-ce délibéré? C'est inattendu que le choix d'un format modifie le contenu renvoyé par une API. (Si c'est délibéré, la doc devrait le mentionner.)

**Comment by jdesboeufs** [comment]
En fait le format GeoJSON implique de choisir une géométrie principale.
Par défaut il s'agit du `centre`.
Cela peut être changé en ajoutant l'option `geometry=contour`.
Les champs `centre` et `contour` ne peuvent pas apparaître dans
`properties`, si on a besoin des deux il suffit de rester au format JSON.

Je regarde pour clarifier la doc.
