### ISSUE TITLE
Pagination des résultats

### ISSUE THREAD

**Issue by steeveb972** [etalab/api-communes#79]
Bonjour,

Je voudrais vous proposer d'implémenter une pagination des résultats qui permettrait en autre pour ceux qui n'ont pas besoin de tout charger de récupérer uniquement ce dont ils ont besoin (ex: uniquement les 10 premiers). En général, les API implémentent cela à l'aide de 2 paramètres offset/limit.
Comme ça, en cas de besoin, il est toujours possible de parcourir les autres résultats.

Merci de votre aide!

**Comment by jon-ht** [comment]
Bonjour,

Est-ce qu'il serait possible d'ajouter le paramètre `offset` ou `page` ? Car actuellement on ne peut pas réellement paginer les résultats.

Merci pour cette API
