### ISSUE TITLE
Déterminants manquants

### ISSUE THREAD

**Issue by Zecat** [etalab/api-communes#85]
Il manque au jeu de données tous les déterminants dans les noms villes.

Exemple, https://geo.api.gouv.fr/communes?codePostal=17000&nom=Rochelle&fields=nom retourne
```json
[{"nom":"Rochelle","code":"17300"}]
```
et devrait retourner
```json
[{"nom":"La Rochelle","code":"17300"}]
```

**Comment by jdesboeufs** [comment]
Merci pour votre retour.
Nous sommes sur le point de modifier notre référentiel source, qui inclura les noms complets.

Je laisse bien sûr ce ticket ouvert.

**Comment by Zecat** [comment]
Parfait ! Merci pour votre réponse rapide.

**Comment by jdesboeufs** [comment]
Même problème avec la commune "Le Gosier" qui est affichée en tant que "Gosier".

**Comment by jdesboeufs** [comment]
Finalement nous sommes toujours sur les fichiers INSEE, mais la typographie a été corrigée.
